# Generated by Django 5.2.17 on 2026-08-17 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0005_repository_monitoring_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, default='local', max_length=100)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_index=True, max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('content', models.JSONField(default=dict)),
                ('rule_version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ('-period_end',),
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'report_type', 'period_start', 'period_end', 'rule_version'), name='unique_scheduled_report_period')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, default='local', max_length=100)),
                ('name', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'watchlists',
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'name'), name='unique_owner_watchlist')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, default='local', max_length=100)),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('REMOVED', 'Removed')], max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
            ],
            options={
                'db_table': 'watchlist_events',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('STAR_GROWTH_SPIKE', 'Star growth spike'), ('FORK_GROWTH_SPIKE', 'Fork growth spike'), ('TREND_CHANGE', 'Trend change'), ('POTENTIAL_CHANGE', 'Potential change'), ('NEW_RELEASE', 'New release'), ('ACTIVITY_SURGE', 'Activity surge'), ('PROJECT_DORMANT', 'Project dormant'), ('NEW_HIGH_POTENTIAL_PROJECT', 'High potential')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('evidence', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('DISMISSED', 'Dismissed')], db_index=True, default='UNREAD', max_length=12)),
                ('rule_version', models.CharField(max_length=50)),
                ('event_bucket', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='repositories.repository')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ('-detected_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('repository', 'alert_type', 'rule_version', 'event_bucket'), name='unique_repository_alert_event')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='watchlists.watchlist')),
            ],
            options={
                'db_table': 'watchlist_items',
                'constraints': [models.UniqueConstraint(fields=('watchlist', 'repository'), name='unique_watchlist_repository')],
            },
        ),
    ]
