# Generated by Django 5.2.11 on 2026-08-18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="CategoryTrendMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=50)),
                ("algorithm_version", models.CharField(max_length=50)),
                ("trend_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("repository_count", models.PositiveIntegerField()),
                ("eligible_repository_count", models.PositiveIntegerField()),
                ("data_coverage", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ("data_as_of", models.DateTimeField()),
                ("evidence", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField()),
            ],
            options={"db_table": "category_trend_metrics"},
        ),
        migrations.CreateModel(
            name="DataCapability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(choices=[("STAR_GROWTH_7D", "Star growth 7d"), ("STAR_GROWTH_30D", "Star growth 30d"), ("FORK_GROWTH_7D", "Fork growth 7d"), ("FORK_GROWTH_30D", "Fork growth 30d"), ("MOMENTUM", "Momentum"), ("HYPE_RISK", "Hype risk"), ("CATEGORY_TREND", "Category trend"), ("TREND_CHANGE_ALERT", "Trend change alert"), ("POTENTIAL_CHANGE_ALERT", "Potential change alert"), ("FORECAST_V2_DATA_READINESS", "Forecast V2 data readiness")], max_length=50, unique=True)),
                ("status", models.CharField(choices=[("ACCUMULATING", "Accumulating"), ("READY", "Ready"), ("DEGRADED", "Degraded"), ("DISABLED", "Disabled")], default="ACCUMULATING", max_length=20)),
                ("data_coverage", models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ("algorithm_version", models.CharField(blank=True, max_length=50, null=True)),
                ("reason", models.TextField()),
                ("metrics", models.JSONField(default=dict)),
                ("data_as_of", models.DateTimeField(blank=True, null=True)),
                ("first_ready_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "data_capabilities", "ordering": ("name",)},
        ),
        migrations.AddConstraint(
            model_name="categorytrendmetric",
            constraint=models.UniqueConstraint(fields=("category", "algorithm_version"), name="unique_category_trend_algorithm"),
        ),
        migrations.AddConstraint(
            model_name="categorytrendmetric",
            constraint=models.CheckConstraint(condition=models.Q(("data_coverage__gte", 0.0), ("data_coverage__lte", 1.0)), name="category_trend_coverage_between_zero_and_one"),
        ),
        migrations.AddConstraint(
            model_name="datacapability",
            constraint=models.CheckConstraint(condition=models.Q(("data_coverage__gte", 0.0), ("data_coverage__lte", 1.0)), name="capability_coverage_between_zero_and_one"),
        ),
    ]
