# Generated by Django 5.2.17 on 2026-08-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubDiscoveryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'github_discovery_queries',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('AGENT_FRAMEWORK', 'Agent framework'), ('CODING_AGENT', 'Coding agent'), ('BROWSER_AGENT', 'Browser agent'), ('RESEARCH_AGENT', 'Research agent'), ('MULTI_AGENT', 'Multi-agent'), ('AGENT_MEMORY', 'Agent memory'), ('AGENT_WORKFLOW', 'Agent workflow'), ('MCP_TOOL', 'MCP tool'), ('COMPUTER_USE', 'Computer use'), ('AGENT_OBSERVABILITY', 'Agent observability'), ('AGENT_SECURITY', 'Agent security'), ('OTHER_AGENT', 'Other agent')], db_index=True, default='OTHER_AGENT', max_length=50)),
                ('stars', models.PositiveBigIntegerField(default=0)),
                ('forks', models.PositiveBigIntegerField(default=0)),
                ('subscribers', models.PositiveBigIntegerField(default=0)),
                ('open_issues', models.PositiveBigIntegerField(default=0)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('license_key', models.CharField(blank=True, max_length=100, null=True)),
                ('license_spdx', models.CharField(blank=True, max_length=100, null=True)),
                ('default_branch', models.CharField(max_length=255)),
                ('repo_size', models.PositiveBigIntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('community_health', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('github_pushed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_synced_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'repositories',
                'ordering': ('-stars', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ('normalized_name',),
            },
        ),
        migrations.CreateModel(
            name='RepositoryTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.topic')),
            ],
            options={
                'db_table': 'repository_topics',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.ManyToManyField(related_name='repositories', through='repositories.RepositoryTopic', to='repositories.topic'),
        ),
        migrations.AddConstraint(
            model_name='repositorytopic',
            constraint=models.UniqueConstraint(fields=('repository', 'topic'), name='unique_repository_topic'),
        ),
    ]
