# Generated by Django 5.2.17 on 2026-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
