# Generated by Django 5.2.17 on 2026-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_seed_discovery_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='forks',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='open_issues',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='subscribers',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
