# Generated by Django 5.2.11 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("repositories", "0007_repository_discover_nulls_last_index")]

    operations = [
        migrations.CreateModel(
            name="RepositoryLocalization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_hash", models.CharField(max_length=64)),
                ("description_zh", models.TextField()),
                ("topics_zh", models.JSONField(default=list)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("status", models.CharField(default="TRANSLATED", max_length=20)),
                ("translated_at", models.DateTimeField(auto_now=True)),
                ("repository", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="zh_localization", to="repositories.repository")),
            ],
            options={"db_table": "repository_localizations"},
        )
    ]
