# Generated by Django 5.2.17 on 2026-08-16 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0004_alter_repository_forks_alter_repository_open_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTrendScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('momentum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('development_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('community_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adoption_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('topic_momentum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maintenance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hype_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hype_risk_status', models.CharField(choices=[('INSUFFICIENT_HISTORY', 'Insufficient history'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=30)),
                ('lifecycle_stage', models.CharField(choices=[('EMERGING', 'Emerging'), ('ACCELERATING', 'Accelerating'), ('BREAKOUT', 'Breakout'), ('GROWING', 'Growing'), ('MATURE', 'Mature'), ('COOLING', 'Cooling'), ('DORMANT', 'Dormant')], max_length=20)),
                ('data_completeness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('algorithm_version', models.CharField(max_length=50)),
                ('calculated_at', models.DateTimeField()),
                ('evidence', models.JSONField(default=dict)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_scores', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_trend_scores',
                'constraints': [models.UniqueConstraint(fields=('repository', 'algorithm_version'), name='unique_repository_trend_algorithm'), models.CheckConstraint(condition=models.Q(('data_completeness__gte', 0.0), ('data_completeness__lte', 1.0)), name='trend_completeness_between_zero_and_one')],
            },
        ),
    ]
