# Generated by Django 5.2.17 on 2026-08-17 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0005_repository_monitoring_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryLearningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('algorithm_version', models.CharField(max_length=50)),
                ('evidence', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_scores', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_learning_scores',
                'constraints': [models.UniqueConstraint(fields=('repository', 'algorithm_version'), name='unique_repository_learning_algorithm'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='learning_confidence_between_zero_and_one')],
            },
        ),
    ]
