# Generated by Django 5.2.17 on 2026-08-17 12:37

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0005_repository_monitoring_fields'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('README', 'README'), ('DOC', 'Documentation'), ('ARCHITECTURE', 'Architecture'), ('DESIGN', 'Design'), ('SECURITY', 'Security'), ('CONTRIBUTING', 'Contributing'), ('RELEASE', 'Release'), ('PULL_REQUEST', 'Pull request'), ('ISSUE', 'Issue')], max_length=30)),
                ('source_path', models.CharField(max_length=1000)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('source_url', models.TextField()),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='repositories.repository')),
            ],
            options={
                'db_table': 'knowledge_documents',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('heading_path', models.CharField(blank=True, max_length=1500)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_version', models.CharField(max_length=50)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='repositories.repository')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(default='PENDING', max_length=30)),
                ('last_stats', models.JSONField(default=dict)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sync_state', to='repositories.repository')),
            ],
            options={
                'db_table': 'knowledge_sync_states',
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('repository', 'source_type', 'external_id'), name='unique_repository_knowledge_source'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index', 'embedding_version'), name='unique_document_chunk_embedding_version'),
        ),
    ]
