# Generated by Django 5.2.17 on 2026-08-16 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0004_alter_repository_forks_alter_repository_open_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField()),
                ('snapshot_date', models.DateField(db_index=True)),
                ('snapshot_bucket', models.CharField(max_length=13)),
                ('stars', models.PositiveBigIntegerField(blank=True, null=True)),
                ('forks', models.PositiveBigIntegerField(blank=True, null=True)),
                ('subscribers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('open_issues', models.PositiveBigIntegerField(blank=True, null=True)),
                ('github_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('data_completeness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_snapshots',
                'ordering': ('-snapshot_at',),
                'constraints': [models.UniqueConstraint(fields=('repository', 'snapshot_bucket'), name='unique_repository_snapshot_bucket'), models.CheckConstraint(condition=models.Q(('data_completeness__gte', 0.0), ('data_completeness__lte', 1.0)), name='snapshot_completeness_between_zero_and_one')],
            },
        ),
    ]
