# Generated by Django 5.2.11 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("repositories", "0007_repository_discover_nulls_last_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repository_comments", to=settings.AUTH_USER_MODEL)),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="community_comments", to="repositories.repository")),
            ],
            options={"db_table": "repository_comments", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="RepositoryLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="community_likes", to="repositories.repository")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repository_likes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "repository_likes"},
        ),
        migrations.AddIndex(model_name="repositorycomment", index=models.Index(fields=["repository", "-created_at"], name="repo_comment_time_idx")),
        migrations.AddIndex(model_name="repositorylike", index=models.Index(fields=["repository", "-created_at"], name="repo_like_time_idx")),
        migrations.AddConstraint(model_name="repositorylike", constraint=models.UniqueConstraint(fields=("repository", "user"), name="unique_repository_like_user")),
    ]
