# Generated by Django 5.2.17 on 2026-08-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0004_alter_repository_forks_alter_repository_open_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contributors',
            },
        ),
        migrations.CreateModel(
            name='RepositoryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_release_id', models.BigIntegerField(unique=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('name', models.TextField(blank=True, null=True)),
                ('author_login', models.CharField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_prerelease', models.BooleanField(default=False)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_releases',
            },
        ),
        migrations.CreateModel(
            name='RepositoryActivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('commits_7d', models.PositiveIntegerField(blank=True, null=True)),
                ('commits_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('commits_90d', models.PositiveIntegerField(blank=True, null=True)),
                ('prs_created_7d', models.PositiveIntegerField(blank=True, null=True)),
                ('prs_created_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('prs_merged_7d', models.PositiveIntegerField(blank=True, null=True)),
                ('prs_merged_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_created_7d', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_created_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_closed_7d', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_closed_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('active_contributors_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('releases_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('releases_90d', models.PositiveIntegerField(blank=True, null=True)),
                ('days_since_last_push', models.PositiveIntegerField(blank=True, null=True)),
                ('days_since_last_release', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_activity_metrics',
                'constraints': [models.UniqueConstraint(fields=('repository', 'metric_date'), name='unique_repository_activity_date')],
            },
        ),
        migrations.CreateModel(
            name='RepositoryContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions_total', models.PositiveIntegerField(blank=True, null=True)),
                ('last_observed_at', models.DateTimeField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_contributors',
                'constraints': [models.UniqueConstraint(fields=('repository', 'contributor'), name='unique_repository_contributor')],
            },
        ),
    ]
